server:
  port: 9999
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/heartsound?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: sl1056160782

mybatis:
  type-aliases-package: com.heartsound.common #别名扫描包
  mapper-locations: classpath:/mapper/*.xml #Mapper.Xml文件地址
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
